name: Run Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run --config baseUrl=https://justin-wilkins.netlify.app

      - name: Generate Test Results JSON
        run: |
          mkdir -p cypress/results
          ls -la cypress # Check if the folder was created
          # Generate your JSON file from Cypress results
          npx cypress run --reporter json --reporter-options output=cypress/results/test-results.json
          ls -la cypress/results # Check the contents of the 'results' folder

      - name: Upload Test Results to Netlify
        run: |
          curl -X POST -F "file=@cypress/results/test-results.json" https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys --header "Authorization: Bearer ${{ secrets.NETLIFY_API_KEY }}"
          
  deploy:
    runs-on: ubuntu-latest
    needs: cypress-run  # Ensures that the deploy job only runs after the tests have completed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --dir=public # Path to your public directory
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
