name: Run Cypress Tests and Update Website with Mochawesome Report

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git configuration
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"

    - name: Clear cache before test run
      run: rm -rf node_modules/.cache

    - name: Remove old Mochawesome reports
      run: rm -rf src/html-report/*
        
    - name: Install dependencies and run tests
      run: |
        npm install
        npm run test --reporter mochawesome --reporter-options reportDir=src/html-report,reportFilename=mochawesome.json
      continue-on-error: true

    - name: Stash local changes
      run: git stash --include-untracked

    - name: Pull latest changes
      run: git pull --rebase origin main
  
    - name: Apply stashed changes
      run: git stash pop || echo "No changes to apply"

    - name: Pull latest changes
      run: git pull --rebase origin main
        
    - name: Stage and commit mochawesome report
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git commit -m "Add Mochawesome report"
        git checkout main
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Ensure changes are pushed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git commit -m "Update Mochawesome report" || echo "No changes to commit"
        git push origin main

    - name: Check mochawesome.json after Cypress tests
      run: cat src/html-report/mochawesome.json
