name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install 

    - name: Run Cypress tests with MochaAwesome
      run: npx cypress run

    - name: Merge Mochawesome Reports
      run: npx mochawesome-merge results/*.json > results/mochawesome.json

    - name: Generate HTML Report
      run: npx marge results/mochawesome.json --reportDir results/html-report

    - name: Upload Cypress results
      uses: actions/upload-artifact@v2
      with:
        name: cypress-results
        path: results/**
