name: Run Cypress Tests and Update Website with Mochawesome Report

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git configuration
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"

    - name: Clear cache before test run
      run: rm -rf node_modules/.cache

    - name: Remove old Mochawesome reports
      run: rm -rf src/html-report/* || echo "No reports to remove"

    - name: Install dependencies and run tests
      run: |
        npm install
        npm run test --reporter mochawesome --reporter-options reportDir=src/html-report,reportFilename=mochawesome.json
      continue-on-error: true

    - name: Ensure mochawesome.json exists
      run: ls -l src/html-report/ || echo "Mochawesome report directory not found"

    - name: Commit and push mochawesome report
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git add -A
          git commit -m "Update Mochawesome report"
          git push origin main
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify mochawesome.json contents
      run: cat src/html-report/mochawesome.json || echo "Mochawesome report not found"
