name: Run Cypress Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run --config baseUrl=https://justin-wilkins.netlify.app

      - name: Upload Cypress Test Results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results
